server:
  port: 8081
spring:
  thymeleaf:
    cache: false
  datasource:
    username: your DB username
    password: your DB password
    url: jdbc:mysql://your DB address/bysj?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    username: 304711385@qq.com
    password: icjjhymtouqdbhfb
    host: smtp.qq.com
    properties:
      mail:
        smtp:
          ssl:
            enable: true
